apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: glogs
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/kitagry/kubectl-glogs/releases/download/v0.1.0/glogs_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./glogs"
      to: "."
    - from: LICENSE
      to: "."
    bin: "glogs"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/kitagry/kubectl-glogs/releases/download/v0.1.0/glogs_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./glogs"
      to: "."
    - from: LICENSE
      to: "."
    bin: "glogs"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/kitagry/kubectl-glogs/releases/download/v0.1.0/glogs_windows_amd64.zip
    sha256: ""
    files:
    - from: "/glogs.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "glogs.exe"
  shortDescription: A new plugin
  homepage: https://github.com/kitagry/kubectl-glogs
  caveats: |
    Usage:
      $ kubectl glogs

    For additional options:
      $ kubectl glogs --help
      or https://github.com/kitagry/kubectl-glogs/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
